service: ml-serverless-inference

frameworkVersion: '3'

custom:
  modelBucketName: codewave-${sls:stage}-ml-models
  modelObjectKey: models/mlr_mpg_v1.joblib

provider:
  name: aws
  ecr:
    images:
      appimage:
        path: ./

  stage: dev
  region: eu-west-1
  timeout: 300

  environment:
    LOG_LEVEL: ${env:LOG_LEVEL, 'INFO'}
    MODEL_BUCKET_NAME: ${self:custom.modelBucketName}
    MODEL_OBJECT_KEY: ${self:custom.modelObjectKey}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource: "arn:aws:s3:::${self:custom.modelBucketName}/${self:custom.modelObjectKey}"

functions:
  predict:
    image:
      name: appimage
    architecture: arm64
    events:
      - httpApi:
          path: /predict
          method: post


resources:
  Resources:
    MlModelsBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:custom.modelBucketName}
        VersioningConfiguration:
          Status: Enabled
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
